version: "3"
services:
  app:
    build: .
    command: bundle exec hanami server --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "2300:2300"
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
